# Generated by Django 4.1.2 on 2022-12-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_id',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roomno',
            field=models.CharField(blank=True, default='NA', max_length=2),
        ),
    ]
