# Generated by Django 4.1.2 on 2022-12-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0003_student_reg_id_student_roomno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roomno',
            new_name='room_no',
        ),
    ]
