# Generated by Django 4.1.4 on 2022-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0006_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=70)),
                ('l_name', models.CharField(max_length=70)),
                ('e_mail', models.EmailField(max_length=122, unique=True)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('Gender', models.CharField(max_length=10)),
                ('institute_name', models.CharField(max_length=70)),
                ('perm_address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('pinCode', models.IntegerField()),
                ('state', models.CharField(max_length=70)),
                ('workshop', models.CharField(max_length=70)),
                ('purpose', models.CharField(max_length=70)),
                ('duration', models.IntegerField()),
                ('roomno', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
