# Generated by Django 4.1.2 on 2023-01-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0009_guest_arrival_date_guest_leaving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pastguest',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
