# Generated by Django 4.1.2 on 2023-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0010_alter_guest_duration_alter_pastguest_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
