# Generated by Django 4.1.2 on 2023-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0011_alter_guest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='reg_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pastguest',
            name='reg_number',
            field=models.IntegerField(null=True),
        ),
    ]
