# Generated by Django 4.1.2 on 2023-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0012_guest_reg_number_pastguest_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='arrival_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='alumni',
            name='leaving_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='student',
            name='arrival_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='student',
            name='leaving_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
    ]
