# Generated by Django 4.1.2 on 2023-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bprimapp', '0013_alumni_arrival_year_alumni_leaving_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Institute',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='alumni',
            name='father_occupation',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='alumni',
            name='locl_grd',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='alumni',
            name='locl_grd_add',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='alumni',
            name='recommend',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='Institute',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='locl_grd',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='locl_grd_add',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='recommend',
            field=models.CharField(default='NA', max_length=70),
        ),
    ]
